"""HCL generator for Jamf Pro resources."""
from typing import Dict, Any, Optional
import json


class HCLGenerator:
    """Generates Terraform HCL from Jamf Pro resource data."""
    
    def __init__(self):
        self.templates = {
            'policies': self._generate_policy_hcl,
            'scripts': self._generate_script_hcl,
            'packages': self._generate_package_hcl,
            'categories': self._generate_category_hcl,
            'buildings': self._generate_building_hcl,
            'config-profiles': self._generate_config_profile_hcl,
            'smart-groups': self._generate_computer_group_hcl,
            'jamf-app-catalog': self._generate_app_catalog_hcl,
        }
    
    def generate_resource_hcl(self, resource_type: str, resource_data: dict, resource_name: Optional[str] = None) -> str:
        """
        Generate HCL for a single resource.
        
        Args:
            resource_type: Type of resource
            resource_data: Full resource data from Jamf API
            resource_name: Optional Terraform resource name (defaults to sanitized name)
            
        Returns:
            HCL string for the resource
        """
        if resource_type not in self.templates:
            return f"# Unsupported resource type: {resource_type}\n"
        
        generator_func = self.templates[resource_type]
        return generator_func(resource_data, resource_name)



    def _generate_app_catalog_hcl(self, app_data: dict, resource_name: Optional[str] = None) -> str:
        """
        Generate HCL for a Jamf App Catalog app (App Installer).
        Note: Current Terraform provider support for App Installers is limited.
        """
        name = app_data.get('name', 'Unnamed App')
        tf_name = resource_name or self._sanitize_name(name)
        app_details = app_data.get('app', {})
        bundle_id = app_details.get('bundleId', '')
        version = app_details.get('latestVersion', '')
        
        hcl = [f'# Jamf App Catalog: {name}']
        hcl.append(f'# Bundle ID: {bundle_id}')
        hcl.append(f'# Version: {version}')
        hcl.append(f'# Note: App Installers resource is not yet fully supported in Terraform provider')
        hcl.append(f'resource "jamfpro_app_installer" "{tf_name}" {{')
        hcl.append(f'  name                  = "{name}"')
        hcl.append(f'  target_group_id       = {app_data.get("smartGroup", {}).get("id", "null")}')
        hcl.append(f'  deployment_type       = "{app_data.get("deploymentType", "SELF_SERVICE")}"')
        hcl.append(f'  update_behavior       = "{app_data.get("updateBehavior", "AUTOMATIC")}"')
        hcl.append('}')
        
        return '\n'.join(hcl)
    
    def generate_file(self, resources_sorted: list) -> str:
        """
        Generate complete .tf file with all resources in dependency order.
        
        Args:
            resources_sorted: List of (resource_type, resource_data) tuples
            
        Returns:
            Complete HCL file content
        """
        hcl_blocks = []
        hcl_blocks.append("# Generated by JamfTerraform Proporter\n")
        hcl_blocks.append("# Contains Jamf Pro resources exported from your instance\n\n")
        
        for resource_type, resource_data in resources_sorted:
            hcl = self.generate_resource_hcl(resource_type, resource_data)
            hcl_blocks.append(hcl)
            hcl_blocks.append("\n")
        
        return "\n".join(hcl_blocks)
    
    def _sanitize_name(self, name: str) -> str:
        """Convert resource name to valid Terraform identifier."""
        # Replace spaces and special chars with underscores
        sanitized = name.lower().replace(' ', '_').replace('-', '_')
        # Remove any non-alphanumeric chars except underscores
        sanitized = ''.join(c if c.isalnum() or c == '_' else '' for c in sanitized)
        # Ensure it starts with a letter
        if sanitized and not sanitized[0].isalpha():
            sanitized = 'r_' + sanitized
        return sanitized or 'unnamed_resource'
    
    def _generate_policy_hcl(self, policy_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a Jamf Pro policy."""
        general = policy_data.get('general', {})
        name = general.get('name', 'Unnamed Policy')
        tf_name = resource_name or self._sanitize_name(name)
        
        hcl = [f'resource "jamfpro_policy" "{tf_name}" {{']
        hcl.append(f'  name    = "{name}"')
        hcl.append(f'  enabled = {str(general.get("enabled", True)).lower()}')
        
        # Category
        category = general.get('category', {})
        if isinstance(category, dict) and category.get('id', -1) not in [-1, 0]:
            cat_name = self._sanitize_name(category.get('name', ''))
            hcl.append(f'  category_id = jamfpro_category.{cat_name}.id')
        
        # Frequency
        if 'frequency' in general:
            hcl.append(f'  frequency = "{general["frequency"]}"')
        
        # Scope
        scope = policy_data.get('scope', {})
        if scope:
            hcl.append('')
            hcl.append('  scope {')
            hcl.append(f'    all_computers = {str(scope.get("all_computers", False)).lower()}')
            
            # Computer groups
            comp_groups = scope.get('computer_groups', [])
            if comp_groups:
                group_ids = ', '.join([f'jamfpro_computer_group.{self._sanitize_name(g.get("name", ""))}.id' 
                                      for g in comp_groups if isinstance(g, dict)])
                if group_ids:
                    hcl.append(f'    computer_group_ids = [{group_ids}]')
            
            hcl.append('  }')
        
        # Packages
        packages = policy_data.get('package_configuration', {}).get('packages', [])
        if packages:
            hcl.append('')
            for pkg in packages:
                if isinstance(pkg, dict) and pkg.get('id', -1) not in [-1, 0]:
                    hcl.append('  package {')
                    pkg_name = self._sanitize_name(pkg.get('name', ''))
                    hcl.append(f'    id     = jamfpro_package.{pkg_name}.id')
                    hcl.append(f'    action = "{pkg.get("action", "Install")}"')
                    hcl.append('  }')
        
        # Scripts
        scripts = policy_data.get('scripts', [])
        if scripts:
            hcl.append('')
            hcl.append('  payloads {')
            for script in scripts:
                if isinstance(script, dict) and script.get('id'):
                    hcl.append('    scripts {')
                    script_name = self._sanitize_name(script.get('name', ''))
                    hcl.append(f'      id       = jamfpro_script.{script_name}.id')
                    hcl.append(f'      priority = "{script.get("priority", "After")}"')
                    hcl.append('    }')
            hcl.append('  }')
        
        hcl.append('}')
        return '\n'.join(hcl)
    
    def _generate_script_hcl(self, script_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a Jamf Pro script."""
        name = script_data.get('name', 'Unnamed Script')
        tf_name = resource_name or self._sanitize_name(name)
        
        hcl = [f'resource "jamfpro_script" "{tf_name}" {{']
        hcl.append(f'  name          = "{name}"')
        
        if 'script_contents' in script_data:
            # Escape the script contents
            script_contents = script_data['script_contents'].replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$')
            hcl.append(f'  script_contents = "{script_contents}"')
        
        if 'category' in script_data and script_data['category'].get('id', -1) not in [-1, 0]:
            cat_name = self._sanitize_name(script_data['category'].get('name', ''))
            hcl.append(f'  category_id = jamfpro_category.{cat_name}.id')
        
        hcl.append('}')
        return '\n'.join(hcl)
    
    def _generate_package_hcl(self, package_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a Jamf Pro package."""
        name = package_data.get('name', 'Unnamed Package')
        tf_name = resource_name or self._sanitize_name(name)
        
        hcl = [f'resource "jamfpro_package" "{tf_name}" {{']
        hcl.append(f'  package_name = "{name}"')
        
        if 'filename' in package_data:
            hcl.append(f'  filename = "{package_data["filename"]}"')
        
        if 'category' in package_data:
            cat_name = self._sanitize_name(package_data['category'])
            hcl.append(f'  category = "{cat_name}"')
        
        hcl.append('}')
        return '\n'.join(hcl)
    
    def _generate_category_hcl(self, category_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a Jamf Pro category."""
        name = category_data.get('name', 'Unnamed Category')
        tf_name = resource_name or self._sanitize_name(name)
        
        hcl = [f'resource "jamfpro_category" "{tf_name}" {{']
        hcl.append(f'  name = "{name}"')
        
        if 'priority' in category_data:
            hcl.append(f'  priority = {category_data["priority"]}')
        
        hcl.append('}')
        return '\n'.join(hcl)
    
    def _generate_building_hcl(self, building_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a Jamf Pro building."""
        name = building_data.get('name', 'Unnamed Building')
        tf_name = resource_name or self._sanitize_name(name)
        
        hcl = [f'resource "jamfpro_building" "{tf_name}" {{']
        hcl.append(f'  name = "{name}"')
        
        if 'street_address1' in building_data:
            hcl.append(f'  street_address1 = "{building_data["street_address1"]}"')
        
        if 'city' in building_data:
            hcl.append(f'  city = "{building_data["city"]}"')
        
        hcl.append('}')
        return '\n'.join(hcl)
    
    def _generate_config_profile_hcl(self, profile_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a macOS configuration profile."""
        general = profile_data.get('general', {})
        name = general.get('name', 'Unnamed Profile')
        tf_name = resource_name or self._sanitize_name(name)
        
        hcl = [f'resource "jamfpro_macos_configuration_profile_plist" "{tf_name}" {{']
        hcl.append(f'  name = "{name}"')
        
        if 'description' in general:
            hcl.append(f'  description = "{general["description"]}"')
        
        # Category
        category = general.get('category', {})
        if isinstance(category, dict) and category.get('id', -1) not in [-1, 0]:
            cat_name = self._sanitize_name(category.get('name', ''))
            hcl.append(f'  category_id = jamfpro_category.{cat_name}.id')
        
        hcl.append('  # Note: payloads require manual configuration')
        hcl.append('}')
        return '\n'.join(hcl)
    
    def _generate_computer_group_hcl(self, group_data: dict, resource_name: Optional[str] = None) -> str:
        """Generate HCL for a computer group (static or smart)."""
        name = group_data.get('name', 'Unnamed Group')
        tf_name = resource_name or self._sanitize_name(name)
        is_smart = group_data.get('is_smart', False)
        
        resource_type = "jamfpro_computer_group_smart" if is_smart else "jamfpro_computer_group_static"
        
        hcl = [f'resource "{resource_type}" "{tf_name}" {{']
        hcl.append(f'  name = "{name}"')
        
        if is_smart and 'criteria' in group_data:
            hcl.append('  # Note: criteria require manual configuration')
        
        hcl.append('}')
        return '\n'.join(hcl)
